language: "zh"

pipeline:
- name: "nlp_spacy"
- name: "tokenizer_jieba"
- name: "ner_spacy"
- name: "intent_entity_featurizer_regex"
- name: "ner_crf"
  features: [
            ["low", "title", "upper"],
            ["bias", "upper", "title", "digit", "pattern"],
            ["low", "title", "upper"]
        ]
- name: "intent_featurizer_spacy"
- name: "intent_classifier_sklearn"
